package com.xworkx.exception.runner;

public class ExceptionsRunner {
	public static void main(String[] args) {
		try {
			int[] numbers= {7,3,5,8,6};
			System.out.println("This is Array out of Bounds Exception");
			
			try {
				throw new NameException();
				}catch(NameException name) {
					System.out.println("** Name Custom Exception Occured");
				}
		}
	}

}
